name: Run integration tests
on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: integration test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: test integrationTest
