name: Deploy to Production
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  validation:
    name: 'Gradle Wrapper Validation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  pipeline:
    name: archpad pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 18.18.2
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Install node.js packages
        run: npm install

      - name: Run backend test
        run: |
          chmod +x gradlew
          npm run ci:backend:test

      - name: Package application
        run: npm run java:jar:prod

      - name: Deploy to Heroku
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          if [ ! -z "$HEROKU_API_KEY" ]; then
              ./gradlew deployHeroku --no-daemon
          else
              echo No HEROKU_API_KEY, skipping...
          fi
